config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :boards do
    resources :columns
  end

  resources :cards, only: [:destroy, :index]

  resources :users do
    resources :teams
  end

  namespace :api do
    resources :users
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :columns, dependent: :destroy
  has_many :teams
  has_many :users, through: :teams
  validates :name, presence: true, length: {minimum: 5}
  validates :progress, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :column
end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :board
  has_many :cards, dependent: :destroy
  validates :background_color, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  has_many :teams
  has_many :boards, through: :teams
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ::ApplicationController
    respond_to :json
    skip_before_action :verify_authenticity_token

    def index
      @collection = resource_class.all
      render json: @collection.as_json(as_json_collection)
    end

    private

    def resource_class
      raise NotImplementedError
    end

    def as_json_collection
      {}
    end

  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApiController

    private

    def resource_class
      User
    end

    def resource_params
      params.require(:user).permit(:name, :email)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
    @boards = Board.all
  end

  def edit
    @board = Board.find(params[:id])
  end

  def show
    @board = Board.find(params[:id])
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)

    if @board.save
      redirect_to @board
    else
      render 'new'
    end
  end

  def update
    @board = Board.find(params[:id])

    if @board.update(board_params)
      redirect_to @board

    else
      render 'edit'
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_path
  end

  private

  def board_params
    params.require(:board).permit(:name, :description, :background_img,
                                  :background_color, :progress)
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController



  def show
    @column = Column.find(params[:column_id])
    @card = @column.cards.find(params[:id])
  end

  def new
    @card = Card.new
  end

  def create
    @board = Board.find(params[:board_id])
    @column = @board.columns.find(params[:column_id])
    @card = @column.cards.create(card_params)
    redirect_to board_column_path(@board,@column)
  end

  def destroy
    @board = Board.find(params[:board_id])
    @column = @board.columns.find(params[:column_id])
    @card = @column.cards.find(params[:id])
    @card.destroy
    redirect_to board_column_path(@board,@column)
  end

  private
  def card_params
    params.require(:card).permit(:name, :description)
  end

end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController


  def show
    @board = Board.find(params[:board_id])
    @column = @board.columns.find(params[:id])
  end

  def create
    @board = Board.find(params[:board_id])
    @column = @board.columns.create(column_params)
    redirect_to boards_path(@board)
  end

  def update
    @board = Board.find(params[:board_id])
    @column = @board.columns.find(params[:id])

    if @column.update(column_params)
      redirect_to board_columns_path(@board, @column)

    else
      render 'edit'
    end
  end

  def destroy
    @board = Board.find(params[:board_id])
    @column = @board.columns.find(params[:id])
    @column.destroy
    redirect_to board_path(@board)
  end

  private
    def column_params
      params.require(:column).permit(:name, :background_color)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def new
    @team = Team.new
  end

  def create

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :email,
                                  :profile_img)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boards/_form.erb
<%= form_with model: @board, local: true do |form| %>

  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@board.errors.count, "error") %> occurred:
      </h2>
      <ul>
        <% @board.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </p>

  <p>
    <%= form.label :background_img %><br>
    <%= form.text_field :background_img %>
  </p>

  <p>
    <%= form.label :background_color %><br>
    <%= form.text_field :background_color %>
  </p>

  <p>
    <%= form.label :progress %><br>
    <%= form.text_field :progress %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h1>Listing boards</h1>


<%= link_to 'New board', new_board_path %>
<table>
  <tr>
    <th>name</th>
    <th>description</th>
    <th>progress</th>
  </tr>

  <% @boards.each do |board| %>
    <tr>
      <td><%= board.name %></td>
      <td><%= board.description %></td>
      <td><%= board.progress %></td>
      <td><%= link_to 'Show', board_path(board) %></td>
      <td><%= link_to 'Edit', edit_board_path(board) %></td>
      <td><%= link_to 'Destroy', board_path(board),
              method: :delete,
              data: {confirm: 'Are you sure?'}%></td>
    </tr>
  <% end %>

</table>

<%= link_to 'Select another entity', welcome_index_path %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @board.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @board.description %>
</p>

<p>
  <strong>Progress:</strong>
  <%= @board.progress %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %>
<%= link_to 'Back', boards_path %>

<h2>Columns</h2>
<%= render @board.columns %>

<h2>Add a column:</h2>
<%= render 'columns/form' %>

app/views/cards/_card.html.erb
<p>
  <strong>Name:</strong>
  <%= card.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= card.description %>
</p>

<p>
  <%= link_to 'Destroy Card', [card],
              method: :delete,
              data: {confirm: 'Are you sure?'}%>
</p>

app/views/columns/_column.erb
<p>
  <strong>Name:</strong>
  <%= column.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= column.background_color %>
</p>

<%= link_to 'Show Column', [column.board, column] %> 

<p>
  <%= link_to 'Destroy Column', [column.board, column],
                method: :delete,
                data: {confirm: 'Are you sure?'}%>
</p>

app/views/columns/_form.erb
<%= form_with(model: [@board, @board.columns.build], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
<p>
    <%= form.label :background_color %><br>
    <%= form.text_field :background_color %>
</p>
<p>
  <%= form.submit %>
</p>
<% end %>

app/views/columns/edit.html.erb
<h1>Edit column</h1>

<%= form_with(model: edit_board_column_path(@board, @column), local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :background_color %><br>
    <%= form.text_field :background_color %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', board_columns_path(@board, @column) %>

app/views/columns/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @column.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @column.background_color %>
</p>

<%= link_to 'Edit (Fake)'%>
<%= link_to 'Back', board_path(@board) %>

<h2>Cards:</h2>
<%= render @column.cards %>
<h2>Add a card:</h2>
<%= form_with(model: @column.cards.build, local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<%= form_with scope: :user, url: users_path, local:  true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :password %><br>
    <%= form.text_field :password %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :profile_img %><br>
    <%= form.text_field :profile_img %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= link_to 'New user', new_user_path %>

<table>
  <tr>
    <th>name</th>
    <th>email</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),
                      method: :delete,
                      data: {confirm: 'Are you sure?'}%></td>
    </tr>
  <% end %>

</table>

<%= link_to 'Select another entity', welcome_index_path %>

app/views/users/new.html.erb
<%= form_with scope: :user, url: users_path, local:  true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :password %><br>
    <%= form.text_field :password %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :profile_img %><br>
    <%= form.text_field :profile_img %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

app/views/welcome/index.html.erb
<h1>My trello-like app</h1>
<p>Inspect every <strong>independent</strong> entity:</p>
<ul>
  <li><%= link_to 'Boards', controller: 'boards' %></li>
  <li><%= link_to 'Users', controller: 'users' %></li>
</ul>